PUT localhost:4000/patients/6507ec35-6c8e-4fde-b984-a41710aaddc2
Content-Type: application/json

{
  "name":"Nikhil Jatla",
  "email":"njatla@datafrond.com",
  "address":"935 Highlang ave",
  "dateOfBirth":"2003-04-19",
  "registeredDate":"2025-07-29"
}